### ISSUE TITLE
versions <1.0.0> cannot be uploaded with curl

### ISSUE THREAD

**Issue by DmitryZakharov** [ryandoyle/vagrancy#5]
I installed the vagrancy on CentOS 6.8 and trying to upload a box with curl:
curl http://<ip>:8099/user/CentOS68/1.0.1/vsphere --upload-file CentOS-6.8_x86_64_vsphere.box
I get :
 [05/May/2017:14:33:47 +0200] "PUT /user/CentOS68/1.0.1/vsphere HTTP/1.1" 400 23 0.0033
Vagrancy::Helpers::InvalidParameterName - invalid parameter 1.0.1:

any idea ?
if I use ..../CentOS68/1/vsphere instead of 1.0.1 it gets uploaded.

**Comment by ryandoyle** [comment]
Hi @DmitryZakharov, this looks to be regression with the 0.0.3 release. I'll work on a fix and upload a new version soon.

**Comment by ryandoyle** [comment]
I've released 0.0.4 which includes the fix.

Cheers

**Comment by danr777** [comment]
Is this still a relevant project?   I have set it up  but its not accepting .box files when I try to upload to the puma server   using curl on OSX
